language: ruby
rvm: 2.0.0
before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup'
script: rake build
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish'

env:
  global:
    - GIT_COMMITTER_NAME="Kazuhito Hokamura"
    - GIT_COMMITTER_EMAIL="k.hokamura@gmail.com"
    - GIT_AUTHOR_NAME="Kazuhito Hokamura"
    - GIT_AUTHOR_EMAIL="k.hokamura@gmail.com"
    - secure: "Y7ITCa6brTg+0BFFS1HAIHxkk7kmI4OBqjGEbPRDZJqnmlaTDut7l9MTXaR9WnoSKCgaMtobzhhMx7Z5TL/T2sXwGDYsdtCeRtthnvxUKLWQMDK3A5SDoHAWfvRSL2GbhmFCXwjqzSjsAVrNW9eCqn1oDcIcRmzDZw+BlbSc0eU="
