language: ruby
rvm: 2.0.0
before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup'
script: rake build
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish'

env:
  global:
    - GIT_COMMITTER_NAME="Kazuhito Hokamura"
    - GIT_COMMITTER_EMAIL="k.hokamura@gmail.com"
    - GIT_AUTHOR_NAME="Kazuhito Hokamura"
    - GIT_AUTHOR_EMAIL="k.hokamura@gmail.com"
    - secure: "ktBrNKgGgj2t4EStEswoY09jTQ9rh3t0z3cgmprtte6Yr6+5IBhwRl0MeOI6sLEyw/aiUK6FFsMbmRFU+Ad1TqD6PYDlGN+PljTDNWgGMcRTh1NGUYu3rJQYtJOeOLVWLaph553lUwUjS4SuYDvmidUZ3rIaU5ggRgyafmbgtjA="
